import re
import os
import glob

# Master dictionary of Bengali to English replacements
translations = [
    # Flowforge modals & components
    ("রিয়েল-টাইম ব্যান্ডউইথ ও ট্রাফিক অ্যানালাইসিস", "Real-Time Bandwidth & Traffic Analysis"),
    ("সরাসরি রাউটার ইন্টারফেস থেকে লাইভ আপলোড ও ডাউনলোড ট্রাফিকের স্পিড মিটার", "Live upload & download speed meter directly from router interface"),
    ("লাইভ ব্যান্ডউইথ মিটার", "Live Bandwidth Meter"),
    ("টোটাল ডাউনলোড", "Total Download"),
    ("টোটাল আপলোড", "Total Upload"),
    ("পিক ব্যান্ডউইথ", "Peak Bandwidth"),
    ("নেটওয়ার্ক অ্যাক্টিভ কানেকশন", "Network Active Connections"),
    ("রিয়েল-টাইম স্পিড গ্রাফ", "Real-Time Speed Graph"),
    ("রাউটার পোর্ট স্ট্যাটাস", "Router Port Status"),
    ("আইএসপি এআই সহকারী", "ISP AI Assistant"),
    ("আপনার প্রশ্ন বা সমস্যা লিখুন...", "Type your question or issue..."),
    ("পাঠান", "Send"),
    ("সহায়ক পরামর্শ", "Helpful Tips"),
    ("কীভাবে বিল পরিশোধ করব?", "How do I pay my bill?"),
    ("ইন্টারনেট স্পিড কম পেলে কী করব?", "What should I do if internet speed is slow?"),
    ("প্যাকেজ পরিবর্তন করতে চাই", "I want to change my package"),
    ("কানেকশন কাজ করছে না", "My connection is not working"),
    ("হ্যালো! আমি আপনার আইএসপি এআই সহকারী। বিলিং, স্পিড, রাউটার কনফিগারেশন বা যেকোনো টেকনিক্যাল সমস্যায় সাহায্য করতে পারি।", "Hello! I am your ISP AI Assistant. I can assist you with billing, speed optimization, router settings, or any technical queries."),
    ("অনুগ্রহ করে আপনার প্রশ্নটি লিখুন।", "Please type your question."),
    ("এসএমএস রিমাইন্ডার পাঠান", "Send SMS Reminder"),
    ("ক্লায়েন্টকে দ্রুত বিল পরিশোধ ও মেয়াদোত্তীর্ণ নোটিফিকেশন মেসেজ প্রেরণ করুন।", "Send quick payment reminders and expiration notice messages to subscriber."),
    ("প্রাপক গ্রাহক", "Recipient Subscriber"),
    ("মোবাইল নম্বর", "Mobile Number"),
    ("বর্তমান প্যাকেজ", "Current Package"),
    ("বকেয়া বিল", "Due Bill"),
    ("মেয়াদের তারিখ", "Expiry Date"),
    ("মেসেজ টেমপ্লেট নির্বাচন করুন", "Select Message Template"),
    ("এসএমএস বার্তা (Message Body)", "SMS Message Body"),
    ("মেসেজ প্রিভিউ", "Message Preview"),
    ("এসএমএস পাঠান", "Send SMS"),
    ("বাতিল", "Cancel"),
    ("এসএমএস পাঠানো হচ্ছে...", "Sending SMS..."),
    ("সফলভাবে এসএমএস পাঠানো হয়েছে!", "SMS sent successfully!"),
    ("অনুগ্রহ করে সঠিক বার্তা লিখুন", "Please enter a valid message"),
    ("বিল তৈরি ও পেমেন্ট রেকর্ড", "Generate Invoice & Record Payment"),
    ("বিলিং ও ইনভয়েস বিবরণী", "Billing & Invoice Details"),
    ("গ্রাহকের নাম", "Subscriber Name"),
    ("ইউজার আইডি", "User ID"),
    ("প্যাকেজ", "Package"),
    ("বিল পরিমাণ", "Bill Amount"),
    ("পেমেন্ট মেথড", "Payment Method"),
    ("ক্যাশ (Cash)", "Cash"),
    ("বিকাশ (bKash)", "bKash"),
    ("নগদ (Nagad)", "Nagad"),
    ("রকেট (Rocket)", "Rocket"),
    ("ব্যাংক ট্রান্সফার", "Bank Transfer"),
    ("ট্রানজেকশন আইডি (ঐচ্ছিক)", "Transaction ID (Optional)"),
    ("নোট / বিবরণ", "Note / Description"),
    ("সংরক্ষণ করুন", "Save & Record"),
    ("ইনভয়েস প্রিন্ট", "Print Invoice"),
    ("পেমেন্ট সফলভাবে সংরক্ষিত হয়েছে!", "Payment recorded successfully!"),
    ("গ্রাহক লেজার ও ট্রানজেকশন হিস্ট্রি", "Subscriber Ledger & Transaction History"),
    ("সকল বিলিং, পেমেন্ট ও নবায়ন রেকর্ডের সম্পূর্ণ হিসাব", "Complete statement of all billing, payment, and renewal records"),
    ("মোট পরিশোধিত", "Total Paid"),
    ("মোট বকেয়া", "Total Due"),
    ("সর্বশেষ পেমেন্ট", "Last Payment"),
    ("তারিখ", "Date"),
    ("বিবরণ", "Description"),
    ("ডেবিট (বিল)", "Debit (Bill)"),
    ("ক্রেডিট (পেমেন্ট)", "Credit (Payment)"),
    ("ব্যালেন্স", "Balance"),
    ("স্ট্যাটাস", "Status"),
    ("পরিশোধিত", "Paid"),
    ("বকেয়া", "Due"),
    ("লেজার প্রিন্ট করুন", "Print Ledger"),
    ("বন্ধ করুন", "Close"),
    ("এলাকা / জোন ভিত্তিক গ্রাহক তালিকা", "Area / Zone Subscribers View"),
    ("নির্বাচিত এলাকার সক্রিয় ও নিষ্ক্রিয় গ্রাহকদের সার্বিক তথ্য", "Overview of active and inactive subscribers in the selected zone"),
    ("মোট ক্লায়েন্ট", "Total Clients"),
    ("অনলাইন / সক্রিয়", "Online / Active"),
    ("অফলাইন / বকেয়া", "Offline / Due"),
    ("ক্লায়েন্ট নাম", "Client Name"),
    ("ফোন নম্বর", "Phone Number"),
    ("প্যাকেজ নাম", "Package"),
    ("মাসিক বিল", "Monthly Bill"),
    ("মেয়াদের তারিখ", "Expiry Date"),
    ("সংযোগ অবস্থা", "Connection Status"),

    # Admin Profile Page
    ("অ্যাডমিন প্রোফাইল ও অ্যাক্সেস কনফিগারেশন", "Admin Profile & Access Configuration"),
    ("সুপার অ্যাডমিন পরিচয়, লগইন ক্রেডেনশিয়াল ও সিস্টেম অথরাইজেশন সেটিংস", "Super Admin identity, login credentials, and system authorization settings"),
    ("প্রোফাইল তথ্য", "Profile Information"),
    ("পুরো নাম", "Full Name"),
    ("ইমেইল এড্রেস", "Email Address"),
    ("ফোন নম্বর", "Phone Number"),
    ("পদবী / রোল", "Designation / Role"),
    ("পাসওয়ার্ড পরিবর্তন", "Change Password"),
    ("বর্তমান পাসওয়ার্ড", "Current Password"),
    ("নতুন পাসওয়ার্ড", "New Password"),
    ("নিশ্চিত নতুন পাসওয়ার্ড", "Confirm New Password"),
    ("আপডেট ও সংরক্ষণ করুন", "Update & Save Settings"),
    ("সফলভাবে প্রোফাইল আপডেট করা হয়েছে!", "Profile updated successfully!"),

    # Audit Logs
    ("সিস্টেম অডিট ও অ্যাক্টিভিটি লগ", "System Audit & Activity Logs"),
    ("সকল ইউজার অ্যাকশন, মাইক্রোটিক সিঙ্ক, পেমেন্ট রেকর্ড ও সিকিউরিটি লগ ট্র্যাকিং", "Comprehensive tracking of user actions, MikroTik sync, payment records, and security logs"),
    ("লগ ফিল্টার", "Filter Logs"),
    ("সকল ইভেন্ট", "All Events"),
    ("পেমেন্ট ও বিলিং", "Payments & Billing"),
    ("মাইক্রোটিক সিঙ্ক", "MikroTik Sync"),
    ("ইউজার ম্যানেজমেন্ট", "User Management"),
    ("সিকিউরিটি ও লগইন", "Security & Login"),
    ("সময় ও তারিখ", "Timestamp"),
    ("ব্যবহারকারী / রোল", "User / Role"),
    ("ইভেন্টের ধরন", "Event Type"),
    ("বিস্তারিত বিবরণ", "Detailed Description"),
    ("আইপি ঠিকানা", "IP Address"),
    ("সকল লগ মুছুন", "Clear All Logs"),
    ("অডিট লগ এক্সপোর্ট (CSV)", "Export Audit Logs (CSV)"),

    # Bandwidth
    ("ব্যান্ডউইথ প্রোফাইল ম্যানেজমেন্ট", "Bandwidth Profile Management"),
    ("মাইক্রোটিক কিউ (Simple Queue) ও ব্যান্ডউইথ পুল কনফিগারেশন হাব", "MikroTik Simple Queue & Bandwidth Pool Configuration Hub"),
    ("নতুন ব্যান্ডউইথ প্রোফাইল যোগ করুন", "Add New Bandwidth Profile"),
    ("প্রোফাইলের নাম", "Profile Name"),
    ("ডাউনলোড স্পিড (Mbps)", "Download Speed (Mbps)"),
    ("আপলোড স্পিড (Mbps)", "Upload Speed (Mbps)"),
    ("শেয়ারিং রেশিও (Ratio)", "Sharing Ratio"),
    ("প্রোফাইল স্ট্যাটাস", "Profile Status"),
    ("সক্রিয় (Active)", "Active"),
    ("নিষ্ক্রিয় (Inactive)", "Inactive"),
    ("সংরক্ষণ করুন", "Save Profile"),
    ("সম্পাদনা", "Edit"),
    ("মুছে ফেলুন", "Delete"),

    # Billing Page
    ("বিলিং ও ইনভয়েস ম্যানেজমেন্ট", "Billing & Invoice Management"),
    ("সকল গ্রাহকের মাসিক বিল, অটো-ইনভয়েস জেনারেশন, পেমেন্ট কালেকশন ও রিসিট হাব", "Monthly billing, automated invoice generation, payment collections, and receipt hub"),
    ("নতুন বিল তৈরি করুন", "Generate New Bill"),
    ("চলতি মাসের অটো-বিল তৈরি", "Generate Current Month Bills"),
    ("ইনভয়েস আইডি", "Invoice ID"),
    ("বিলিং সাইকেল", "Billing Cycle"),
    ("পরিশোধিত তারিখ", "Payment Date"),
    ("পেমেন্ট স্ট্যাটাস", "Payment Status"),
    ("পরিশোধিত (Paid)", "Paid"),
    ("বকেয়া (Unpaid)", "Unpaid"),
    ("আংশিক (Partial)", "Partial"),
    ("অ্যাকশন", "Actions"),
    ("টাকা জমা নিন", "Collect Payment"),
    ("ইনভয়েস দেখুন", "View Invoice"),

    # Client Dashboard
    ("গ্রাহক সেলফ-কেয়ার ড্যাশবোর্ড", "Subscriber Self-Care Dashboard"),
    ("স্বাগতম", "Welcome"),
    ("আপনার বর্তমান প্যাকেজ", "Your Current Package"),
    ("সংযোগ স্ট্যাটাস", "Connection Status"),
    ("অনলাইন (সক্রিয়)", "Online (Active)"),
    ("অফলাইন (মেয়াদোত্তীর্ণ)", "Offline (Expired)"),
    ("মেয়াদের বাকি দিন", "Days Remaining"),
    ("দ্রুত বিল পরিশোধ (bKash / Nagad)", "Quick Bill Payment (bKash / Nagad)"),
    ("প্যাকেজ আপগ্রেড রিকুয়েস্ট", "Request Package Upgrade"),
    ("অভিযোগ / সাপোর্ট টিকেট", "Submit Support Ticket"),
    ("পেমেন্ট হিস্ট্রি", "Payment History"),

    # Clients
    ("গ্রাহক তালিকা ও ক্লায়েন্ট ম্যানেজমেন্ট", "Subscriber & Client Management"),
    ("ব্রডব্যান্ড গ্রাহকদের পূর্ণাঙ্গ ডাটাবেজ, মেয়াদ ট্র্যাকিং, প্যাকেজ ও রাউটার লিঙ্ক", "Broadband subscriber database, expiry tracking, package assignments, and router links"),
    ("নতুন ক্লায়েন্ট যোগ করুন", "Add New Subscriber"),
    ("বাল্ক গ্রাহক ইমপোর্ট", "Bulk Import Clients"),
    ("এক্সপোর্ট (CSV / Excel)", "Export (CSV / Excel)"),
    ("গ্রাহক অনুসন্ধান করুন...", "Search subscribers by name, phone, IP, or user ID..."),
    ("সকল জোন", "All Zones"),
    ("সকল স্ট্যাটাস", "All Status"),
    ("সক্রিয় ক্লায়েন্ট", "Active Subscribers"),
    ("মেয়াদ শেষ ক্লায়েন্ট", "Expired Subscribers"),
    ("সংযোগ ধরন", "Connection Type"),
    ("PPPoE গ্রাহক", "PPPoE Client"),
    ("Static IP গ্রাহক", "Static IP Client"),
    ("Hotspot গ্রাহক", "Hotspot Client"),

    # Dashboard
    ("আইএসপি কন্ট্রোল ড্যাশবোর্ড", "ISP Control Dashboard"),
    ("রিয়েল-টাইম নেটওয়ার্ক স্ট্যাটাস, লাইভ ক্লায়েন্ট, মেয়াদ অ্যালার্ট ও রাজস্ব ওভারভিউ", "Real-time network status, live subscriber count, expiry alerts, and revenue overview"),
    ("মোট গ্রাহক", "Total Subscribers"),
    ("সক্রিয় সংযোগ", "Active Online"),
    ("মেয়াদোত্তীর্ণ লাইন", "Expired / Offline"),
    ("চলতি মাসের আয়", "Monthly Revenue"),
    ("বকেয়া বিল", "Total Unpaid Due"),
    ("আজকের কালেকশন", "Today's Collection"),
    ("দ্রুত অ্যাকশন", "Quick Actions"),
    ("নতুন বিল তৈরি", "New Bill"),
    ("নতুন ক্লায়েন্ট", "New Client"),
    ("এসএমএস পাঠান", "Send SMS"),
    ("মাইক্রোটিক সিঙ্ক", "MikroTik Sync"),
    ("মেয়াদ শেষ হওয়ার সতর্কতা (Expiring Soon)", "Expiring Soon Alerts"),

    # Days Profile
    ("মেয়াদের প্রোফাইল কনফিগারেশন", "Validity Profile Configuration"),
    ("প্যাকেজের সময়সীমা, বিলিং সাইকেল ও গ্রেস পিরিয়ড ম্যানেজমেন্ট", "Package validity duration, billing cycles, and grace period management"),
    ("নতুন মেয়াদের প্রোফাইল যোগ করুন", "Add New Validity Profile"),
    ("মেয়াদের দিন সংখ্যা", "Duration (Days)"),
    ("গ্রেস পিরিয়ড (দিন)", "Grace Period (Days)"),
    ("ডিফল্ট হিসেবে সেট করুন", "Set as Default"),

    # Expenses Page
    ("আইএসপি খরচ ও অপেক্স ট্র্যাকার", "ISP Expense & OPEX Tracker"),
    ("ব্যান্ডউইথ ফি, অফিস ভাড়া, টেকনিশিয়ান বেতন ও রক্ষণাবেক্ষণ খরচের হিসাব", "Bandwidth uplink fees, office rent, staff salaries, and maintenance expense tracking"),
    ("নতুন খরচ এন্ট্রি করুন", "Add New Expense"),
    ("খরচের ক্যাটাগরি", "Expense Category"),
    ("খরচের পরিমাণ", "Expense Amount"),
    ("খরচের বিবরণ", "Expense Description"),
    ("ভাউচার / রিসিট নম্বর", "Voucher / Receipt No"),
    ("মোট খরচ", "Total Expenses"),
    ("চলতি মাসের মোট খরচ", "This Month Expenses"),

    # Hotspot
    ("হটস্পট ইউজার ও ভাউচার ম্যানেজমেন্ট", "Hotspot User & Voucher Management"),
    ("মাইক্রোটিক হটস্পট গ্রাহক, কার্ড প্রিন্টিং, অ্যাক্টিভেশন ও প্যাকেজ রিকুয়েস্ট", "MikroTik hotspot clients, card voucher printing, activation, and package requests"),
    ("নতুন হটস্পট ইউজার যোগ করুন", "Add New Hotspot User"),
    ("বাল্ক ভাউচার জেনারেটর", "Bulk Voucher Generator"),
    ("হটস্পট রিকুয়েস্ট তালিকা", "Hotspot Package Requests"),
    ("ইউজারনেম", "Username"),
    ("পাসওয়ার্ড", "Password"),
    ("সময়সীমা", "Validity / Uptime"),
    ("ডাটা লিমিট", "Data Limit"),
    ("ডিভাইস লিমিট (MAC)", "MAC / Device Limit"),
    ("ভাউচার প্রিন্ট করুন", "Print Vouchers"),

    # Hotspot Config
    ("হটস্পট সার্ভার ও পোর্টাল কনফিগারেশন", "Hotspot Server & Portal Configuration"),
    ("লগইন পোর্টাল ব্র্যান্ডিং, পেমেন্ট গেটওয়ে লিঙ্ক ও মাইক্রোটিক প্যারামিটার", "Login portal branding, payment gateway integration, and MikroTik hotspot parameters"),
    ("পোর্টাল ব্র্যান্ডিং নাম", "Portal Branding Name"),
    ("লগইন পেজ হেডার টেক্সট", "Login Page Header Text"),
    ("সহায়তা ফোন নম্বর", "Support Helpline Number"),
    ("বিকাশ মার্চেন্ট নম্বর", "bKash Merchant / Personal No"),
    ("পোর্টাল প্রিভিউ দেখুন", "Preview Hotspot Portal"),

    # Invoice Print Page
    ("মানি রিসিট ও বিলিং ইনভয়েস", "Money Receipt & Billing Invoice"),
    ("অফিসিয়াল প্রিন্ট কপি", "Official Printable Copy"),
    ("গ্রাহকের বিবরণ", "Subscriber Details"),
    ("ইনভয়েস নম্বর", "Invoice No"),
    ("বিলিং বিবরণ", "Billing Description"),
    ("পরিমাণ", "Amount"),
    ("মোট প্রদেয়", "Total Payable"),
    ("অবশিষ্ট বকেয়া", "Balance Due"),
    ("প্রিন্ট করুন", "Print Invoice"),
    ("ডাউনলোড (PDF)", "Download PDF"),

    # ISP Digital Modules
    ("ডিজিটাল আইএসপি মডিউল হাব", "Digital ISP Modules Hub"),
    ("এফটিটিএইচ অপটিক্যাল নেটওয়ার্ক, ওএলটি মনিটরিং, স্প্লিটার ম্যাপিং ও অটোমেশন টুলস", "FTTH optical network, OLT monitoring, splitter mapping, and automated operations tools"),
    ("ওএলটি এবং পন পোর্ট মনিটর", "OLT & PON Port Monitor"),
    ("অপটিক্যাল পাওয়ার ও ডিবিএম (dBm) মিটার", "Optical Power & dBm Signal Meter"),
    ("কোর কালার ও ফাইবার স্প্লাইসিং গাইড", "Fiber Color Coding & Splicing Guide"),
    ("টিজে বক্স ও স্প্লিটার ম্যাপার", "TJ Box & Optical Splitter Mapper"),

    # Live Bandwidth Page
    ("লাইভ নেটওয়ার্ক ব্যান্ডউইথ মনিটর", "Live Network Bandwidth Monitor"),
    ("মাইক্রোটিক ইন্টারফেস ভিত্তিক রিয়েল-টাইম ট্রাফিক গ্রাফ ও ব্যবহার অ্যানালিটিক্স", "MikroTik interface real-time traffic graphs and bandwidth analytics"),
    ("ডাউনলোড স্পিড", "Download Speed"),
    ("আপলোড স্পিড", "Upload Speed"),
    ("লাইভ ব্যান্ডউইথ থ্রুপুট", "Live Bandwidth Throughput"),
    ("রাউটার ট্রাফিক হিস্ট্রি", "Router Traffic History"),

    # MikroTik Management
    ("মাইক্রোটিক রাউটার ও এপিআই সংযোগ", "MikroTik Router & API Management"),
    ("সরাসরি RouterOS API ইন্টিগ্রেশন, PPPoE সিক্রেট সিঙ্ক, আইপি পুল ও কিউ অটোমেশন", "Direct RouterOS API integration, PPPoE secret sync, IP pools, and queue automation"),
    ("রাউটার আইপি এড্রেস", "Router IP Address"),
    ("এপিআই পোর্ট (ডিফল্ট: 8728)", "API Port (Default: 8728)"),
    ("রাউটার ইউজারনেম", "Router Username"),
    ("রাউটার পাসওয়ার্ড", "Router Password"),
    ("কানেকশন টেস্ট করুন", "Test Connection"),
    ("সমস্ত গ্রাহক সিঙ্ক করুন", "Sync All Subscribers"),
    ("সফলভাবে সংযোগ স্থাপিত হয়েছে!", "Connected to MikroTik successfully!"),

    # Network Coverage Map
    ("নেটওয়ার্ক কভারেজ ও পপ (POP) ম্যাপ", "Network Coverage & POP Map"),
    ("আইএসপি জোন, ফাইবার ক্যাবল রুট, অপটিক্যাল নোড ও কভারেজ এলাকার লাইভ ম্যাপ", "ISP zones, fiber cable routes, optical distribution nodes, and coverage area map"),
    ("নতুন পপ (POP) লোকেশন", "Add New POP Location"),
    ("ফাইবার লিংক ড্রয়িং", "Draw Fiber Link"),
    ("এলাকা ভিত্তিক ক্লায়েন্ট ডেনসিটি", "Subscriber Density by Zone"),

    # Notifications
    ("নোটিফিকেশন ও অ্যালার্ট সেন্টার", "Notification & Alert Center"),
    ("মেয়াদোত্তীর্ণ লাইন সতর্কতা, পেমেন্ট রিকুয়েস্ট, সাপোর্ট টিকেট ও সিস্টেম মেসেজ", "Expiration alerts, payment requests, support tickets, and system notifications"),
    ("সকল নোটিফিকেশন", "All Notifications"),
    ("পড়া হয়েছে হিসেবে চিহ্নিত করুন", "Mark All as Read"),
    ("সকল নোটিফিকেশন মুছুন", "Clear All Notifications"),
    ("কোনো নতুন নোটিফিকেশন নেই", "No new notifications"),

    # Packages
    ("ইন্টারনেট প্যাকেজ ম্যানেজমেন্ট", "Internet Package Management"),
    ("ব্রডব্যান্ড ও হটস্পট প্যাকেজ, ব্যান্ডউইথ রেট, মূল্য ও মাইক্রোটিক প্রোফাইল সিঙ্ক", "Broadband and hotspot packages, bandwidth rates, pricing, and MikroTik profile sync"),
    ("নতুন প্যাকেজ তৈরি করুন", "Create New Package"),
    ("প্যাকেজের নাম", "Package Name"),
    ("স্পিড / ব্যান্ডউইথ", "Speed / Bandwidth"),
    ("মাসিক মূল্য (৳)", "Monthly Price (৳)"),
    ("প্যাকেজ টাইপ", "Package Type"),
    ("ব্রডব্যান্ড (PPPoE)", "Broadband (PPPoE)"),
    ("হটস্পট (Hotspot)", "Hotspot"),
    ("মাইক্রোটিক হটস্পট পেজে সিঙ্ক করুন", "Sync to MikroTik Hotspot Portal"),
    ("প্যাকেজ সংরক্ষণ করুন", "Save Package"),

    # Reports
    ("রিপোর্ট ও ব্যবসায়িক অ্যানালিটিক্স", "Reports & Business Analytics"),
    ("মাসিক কালেকশন, রাজস্ব বৃদ্ধি, বকেয়া তালিকা ও ক্লায়েন্ট গ্রোথ স্টেটমেন্ট", "Monthly collections, revenue trends, due accounts, and subscriber growth statements"),
    ("রিপোর্টের ধরন", "Report Type"),
    ("মাসিক আয়-ব্যয় স্টেটমেন্ট", "Monthly Revenue & Expense Statement"),
    ("বকেয়া বিলের তালিকা", "Unpaid Due Client Report"),
    ("প্যাকেজ ভিত্তিক গ্রাহক বিশ্লেষণ", "Subscriber Distribution by Package"),
    ("রিপোর্ট এক্সপোর্ট করুন (PDF / Excel)", "Export Report (PDF / Excel)"),

    # Revenue Tracker
    ("রাজস্ব ও মুনাফা ট্র্যাকার", "Revenue & Profit Tracker"),
    ("দৈনিক কালেকশন, মাসিক আয়, অপেক্স খরচ ও নেট প্রফিট মার্জিন অ্যানালিসিস", "Daily collections, gross revenue, OPEX costs, and net profit margin analysis"),
    ("মোট রাজস্ব আয়", "Gross Revenue"),
    ("মোট পরিচালন ব্যয়", "Total Operating Expenses"),
    ("নেট লাভ (Net Profit)", "Net Profit"),
    ("লাভের মার্জিন", "Profit Margin"),
    ("পেমেন্ট চ্যানেল বিশ্লেষণ", "Payment Channel Breakdown"),

    # Security Page
    ("সিকিউরিটি ও অ্যাক্সেস কন্ট্রোল", "Security & Access Control"),
    ("পিন লক, পাসওয়ার্ড সুরক্ষা, ব্যাকআপ রিকভারি ও সেশন অথেন্টিকেশন", "PIN lock, password protection, backup recovery, and session authentication"),
    ("অ্যাডমিন পিন কোড", "Admin PIN Code"),
    ("জরুরী ব্যাকআপ রিকভারি পিন", "Emergency Backup Recovery PIN"),
    ("অটো লক সময়সীমা", "Auto Lock Timeout"),
    ("নিরাপত্তা সেটিংস সংরক্ষণ করুন", "Save Security Settings"),

    # Settings
    ("আইএসপি সিস্টেম সেটিংস", "ISP System Settings"),
    ("কোম্পানির নাম, লোগো, হেল্পলাইন, পেমেন্ট গেটওয়ে, এসএমএস এপিআই ও রাউটার কনফিগ", "Company name, logo, helpline, payment gateways, SMS API, and router configuration"),
    ("সাধারণ সেটিংস", "General Settings"),
    ("কোম্পানি / আইএসপির নাম", "Company / ISP Name"),
    ("হেল্পলাইন ফোন", "Helpline Phone"),
    ("হোয়াটসঅ্যাপ নম্বর", "WhatsApp Number"),
    ("কারেন্সি সিম্বল", "Currency Symbol"),
    ("এসএমএস গেটওয়ে কনফিগারেশন", "SMS Gateway Configuration"),
    ("পেমেন্ট গেটওয়ে ও বিকাশ মার্চেন্ট", "Payment Gateways & bKash Merchant"),
    ("সেটিংস সংরক্ষণ করুন", "Save Settings"),
]

def run():
    files = glob.glob("src/**/*.*", recursive=True)
    count = 0
    for f in sorted(files):
        with open(f, "r", encoding="utf-8") as file:
            text = file.read()
        orig = text
        for k, v in translations:
            text = text.replace(k, v)
        if text != orig:
            with open(f, "w", encoding="utf-8") as file:
                file.write(text)
            count += 1
            print(f"Master translation updated: {f}")
    print(f"Total files updated: {count}")

run()
